---
title: 什麼都是假的，只有結訓令才是真的！
author: Shihjyun Yeo
date: '2020-04-28'
slug: 什麼都是假的-只有結訓令才是真的
categories:
  - 雜談
tags: []

summary: 「我星期四要請公假開庭，餐盤可能要麻煩大家代替我洗一下」、「我已經非常努力了，但我們學校的資源真的無法讓我跟頂大的人競爭」、「我高中一畢業就出來工作，不知道讀大學到底有什麼用？」
---

### 每個人都有每個人的故事

「我星期四要請公假開庭，餐盤可能要麻煩大家代替我洗一下」、「我已經非常努力了，但我們學校的資源真的無法讓我跟頂大的人競爭」、「我高中一畢業就出來工作，不知道讀大學到底有什麼用？」

這些對話出自於我身邊的鄰兵，可能是一開始太無聊的關係，除了一開始的自我介紹外，菜兵們也會開始談未來、談過去、談價值觀，這是我當兵時覺得最有趣的地方。

每個人生長、求學的環境各有所異，軍隊敲破了平時我所在同溫層，讓我認識來自四面八方的人，或許在聊天的過程中，對方有些想法與我有差異的，但也許是這份差異才讓我覺得有其可貴之處存在，「哇！原來還有人這樣想！」光是有這樣這想法對我來說就是種收穫了，就算他所說的可能是我無法認同的。

### 在軍中呆久了會變笨

這句話並不是沒有根據的，在軍中我讀了一本書叫做 _放空的科學　Elastic Flexible Thinking in a Time of Change_，大致上是在說明大腦的運作方式，激發創意的彈性思維從何而來。

其中有提到腳本式的思考方式會讓大腦變得比較遲鈍，沒有錯！「腰桿挺直，眼睛注視正前方」、「班頭清查人數開始！」軍隊中充滿著這些腳本式的命令動作使得思維在不知不覺中慢慢地僵化了。

### 天兵

團體中總是會有一兩個標新立異、勇於表達向幹部自己意見的人，或許在外面這些行為沒什麼，但在軍中有這些行為的人就有非常高的機率變成所謂的「天兵」。

我自己印象非常深刻的是在退伍前一個月，因為連續三天沒有使用到手機(放福利)，所以有鄰兵受不了直接打電話跟士官長反應，結果是當天手機的確是用到了，但生活變得異常難受，原本班長睜一隻眼閉一隻眼的生活規定突然間全部回歸根本！

我認為見識天兵的所做所為也是當兵的樂趣之一，如果安安穩穩過完實在是太無趣了。

### 結訓

到了今天結訓，最讓我感觸的是在要走之前，二樓隔著安全網還沒退伍弟兄目送著我們離開，當我回頭看著他們，不知道為何十分替他們感到難過，他們還要在部隊中多待上兩到三天，心中感觸非常深，因為我此時明白了一個道理，**什麼都是假的，只有結訓才是真的！**


